name = "NetRC"
uuid = "4ceb92a4-8458-42c6-ac22-7a21adf6253e"
keywords = ["OPeNDAP", "climate"]
desc = "Reading and creating .netrc files to access OPeNDAP and open-source NetCDF files"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
